import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Sidebar from '../components/Sidebar'
import PageHeader from '../components/PageHeader'
import StatusDot from '../components/StatusDot'
import CVStatusBadge from '../components/cv/CVStatusBadge'
import { jobs, clients, recruiters, activityLogs, PIPELINE_STAGES, STAGE_LABELS } from '../data/mockData'
import { useCandidateContext } from '../context/CandidateContext'
import { initialReminders } from '../data/remindersMockData'
import { formatDate, formatSalary, daysUntil, TODAY } from '../utils/format'
import type { Candidate, PipelineStage } from '../types'

function formatOutputLabel(fmt: string) {
  return fmt === 'both' ? 'DOCX + PDF' : fmt.toUpperCase()
}

function downloadCV(c: Candidate) {
  const lines = [
    `════════════════════════════════════════`,
    `  ${c.name}`,
    `  ${c.email}${c.phone ? ' · ' + c.phone : ''}`,
    `  ${c.address || c.location}`,
    `════════════════════════════════════════`,
    '',
    'SKILLS',
    '─────────────────────────────────────────',
    c.skills.join(' · '),
    '',
    ...(c.workExperience?.length ? [
      'WORK EXPERIENCE',
      '─────────────────────────────────────────',
      ...c.workExperience.map((e) => [
        `${e.position} @ ${e.company}`,
        `${e.startDate} – ${e.isCurrent ? 'Present' : e.endDate}`,
        e.description,
        '',
      ].join('\n')),
    ] : []),
    ...(c.education?.length ? [
      'EDUCATION',
      '─────────────────────────────────────────',
      ...c.education.map((e) => `${e.degree}, ${e.major} — ${e.institution} (${e.graduationYear})`),
      '',
    ] : []),
    ...(c.languages?.length ? [
      'LANGUAGES',
      '─────────────────────────────────────────',
      ...c.languages.map((l) => `${l.language} (${l.level})`),
      '',
    ] : []),
    ...(c.certifications?.length ? [
      'CERTIFICATIONS',
      '─────────────────────────────────────────',
      ...c.certifications.map((cert) => `${cert.name} — ${cert.organization} (${cert.date})`),
      '',
    ] : []),
    `────────────────────────────────────────`,
    `Generated by RecruitSync${c.cvTemplateName ? ' · Template: ' + c.cvTemplateName : ''}`,
  ]
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${c.name.replace(/ /g, '_')}_CV.txt`
  a.click()
  URL.revokeObjectURL(url)
}

const stageBadge: Record<PipelineStage, string> = {
  sourced:   'bg-slate-100 text-slate-600',
  screening: 'bg-blue-100 text-blue-700',
  interview: 'bg-teal-100 text-teal-700',
  offered:   'bg-purple-100 text-purple-700',
  placed:    'bg-green-100 text-green-700',
  rejected:  'bg-red-100 text-red-600',
}

type Tab = 'overview' | 'activity' | 'reminders'

export default function CandidateProfilePage() {
  const { candidateId } = useParams<{ candidateId: string }>()
  const navigate = useNavigate()
  const [tab, setTab] = useState<Tab>('overview')
  const { candidates } = useCandidateContext()

  const candidate = candidates.find((c) => c.id === candidateId)
  if (!candidate) return (
    <div className="flex h-screen items-center justify-center text-slate-400">Candidate not found.</div>
  )

  const job    = jobs.find((j) => j.id === candidate.jobId)
  const client = clients.find((cl) => cl.id === job?.clientId)
  const rec    = recruiters.find((r) => r.id === candidate.recruiterId)

  const stageIdx   = PIPELINE_STAGES.indexOf(candidate.stage)
  const isRejected = candidate.stage === 'rejected'

  // Activity: logs targeting this candidate's job (old data) or mentioning their name
  const relatedLogs = activityLogs.filter(
    (l) => l.targetId === candidate.jobId || l.summary.toLowerCase().includes(candidate.name.toLowerCase())
  )

  const relatedReminders = initialReminders.filter((r) => r.candidateId === candidate.id)
  const openReminders    = relatedReminders.filter((r) => r.status === 'open')
  const doneReminders    = relatedReminders.filter((r) => r.status === 'completed')

  const TABS: { key: Tab; label: string; count?: number }[] = [
    { key: 'overview',  label: 'Overview' },
    { key: 'activity',  label: 'Activity',  count: relatedLogs.length },
    { key: 'reminders', label: 'Reminders', count: openReminders.length },
  ]

  return (
    <div className="flex h-screen bg-slate-50 overflow-hidden">
      <Sidebar />
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        <PageHeader
          title={candidate.name}
          subtitle={`${candidate.location} · ${candidate.experienceYears} yrs experience`}
          breadcrumbs={[
            { label: 'Candidates', to: '/candidates' },
            { label: candidate.name },
          ]}
          actions={
            <button
              onClick={() => navigate(`/jobs/${candidate.jobId}/pipeline`)}
              className="flex items-center gap-1.5 bg-primary text-white text-sm font-semibold px-4 py-1.5 rounded-lg hover:bg-primary-dark transition-colors"
            >
              <span className="material-symbols-outlined" style={{ fontSize: '15px' }}>view_kanban</span>
              View Pipeline
            </button>
          }
        />

        {/* Profile header strip */}
        <div className="bg-white border-b border-slate-200 px-6 py-3 flex items-center gap-4 flex-shrink-0">
          <div className="w-9 h-9 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
            <span className="text-sm font-bold text-primary">{candidate.name.charAt(0)}</span>
          </div>
          <div className="flex items-center gap-2 flex-wrap flex-1">
            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${stageBadge[candidate.stage]}`}>
              {STAGE_LABELS[candidate.stage]}
            </span>
            {job && (
              <button onClick={() => navigate(`/jobs/${job.id}`)} className="text-xs text-primary hover:underline font-medium">
                {job.title}
              </button>
            )}
            {client && (
              <>
                <span className="text-slate-300 text-xs">·</span>
                <button onClick={() => navigate(`/clients/${client.id}`)} className="text-xs text-slate-500 hover:text-primary transition-colors">
                  {client.companyName}
                </button>
              </>
            )}
            <span className="text-slate-300 text-xs">·</span>
            <StatusDot lastActivityDate={candidate.lastActivityDate} reminderOverdue={candidate.reminderOverdue} />
          </div>
          {/* Tabs */}
          <div className="flex gap-1 ml-auto">
            {TABS.map(({ key, label, count }) => (
              <button key={key} onClick={() => setTab(key)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${tab === key ? 'bg-primary/10 text-primary' : 'text-slate-500 hover:bg-slate-100'}`}>
                {label}
                {count !== undefined && count > 0 && (
                  <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-bold ${tab === key ? 'bg-primary text-white' : 'bg-slate-200 text-slate-500'}`}>{count}</span>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* Tab content */}
        <div className="flex-1 overflow-y-auto p-6">

          {/* ── OVERVIEW ── */}
          {tab === 'overview' && (
            <div className="grid grid-cols-12 gap-5 max-w-5xl">

              {/* Left column */}
              <div className="col-span-4 space-y-4">
                {/* Identity */}
                <div className="bg-white rounded-xl border border-slate-200 p-5">
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Contact</p>
                  <div className="space-y-2.5 text-sm">
                    {[
                      { icon: 'location_on', text: candidate.location },
                      { icon: 'mail',        text: candidate.email },
                      ...(candidate.phone ? [{ icon: 'call', text: candidate.phone }] : []),
                      { icon: 'work_history',text: `${candidate.experienceYears} years experience` },
                      { icon: 'calendar_today', text: `Applied ${formatDate(candidate.appliedDate)}` },
                    ].map(({ icon, text }) => (
                      <div key={icon} className="flex items-center gap-2.5 text-slate-600">
                        <span className="material-symbols-outlined text-slate-300" style={{ fontSize: '15px' }}>{icon}</span>
                        <span className="text-xs">{text}</span>
                      </div>
                    ))}
                  </div>
                  <div className="mt-4 pt-4 border-t border-slate-100">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Skills</p>
                    <div className="flex flex-wrap gap-1.5">
                      {candidate.skills.map((s) => (
                        <span key={s} className="text-xs bg-primary/5 text-primary font-medium px-2 py-0.5 rounded-full">{s}</span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Assignment */}
                <div className="bg-white rounded-xl border border-slate-200 p-5">
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Assignment</p>
                  <div className="space-y-3 text-sm">
                    <div>
                      <p className="text-[10px] text-slate-400 mb-0.5">Position</p>
                      <button onClick={() => navigate(`/jobs/${job?.id}`)} className="text-sm font-semibold text-primary hover:underline text-left">{job?.title}</button>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 mb-0.5">Client</p>
                      <button onClick={() => navigate(`/clients/${client?.id}`)} className="text-sm font-medium text-slate-700 hover:text-primary text-left">{client?.companyName}</button>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 mb-0.5">Recruiter</p>
                      <p className="text-sm text-slate-700">{rec?.name}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 mb-0.5">Salary Range</p>
                      <p className="text-sm font-mono font-medium text-slate-700">
                        {job ? `${formatSalary(job.salaryMin)}–${formatSalary(job.salaryMax)}` : '—'}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Generated CV */}
                <div className="bg-white rounded-xl border border-slate-200 p-5">
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Generated CV</p>
                  {candidate.cvTemplateName ? (
                    <div className="space-y-3 text-sm">
                      <div>
                        <p className="text-[10px] text-slate-400 mb-0.5">Template</p>
                        <p className="text-sm font-semibold text-slate-700">{candidate.cvTemplateName}</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono font-bold text-slate-600 bg-slate-100 px-2 py-0.5 rounded">
                          {formatOutputLabel(candidate.cvOutputFormat ?? 'pdf')}
                        </span>
                        {candidate.cvStatus && <CVStatusBadge status={candidate.cvStatus} />}
                      </div>
                      <div>
                        <p className="text-[10px] text-slate-400 mb-0.5">Generated</p>
                        <p className="text-sm text-slate-700">{candidate.cvGeneratedAt ? formatDate(candidate.cvGeneratedAt) : '—'}</p>
                      </div>
                    </div>
                  ) : (
                    <p className="text-xs text-slate-400">No CV has been generated for this candidate yet — you can still download a CV built from their profile data.</p>
                  )}
                  <button
                    onClick={() => downloadCV(candidate)}
                    className="mt-4 w-full flex items-center justify-center gap-1.5 bg-success text-white text-xs font-semibold py-2 rounded-lg hover:opacity-90 transition-opacity"
                  >
                    <span className="material-symbols-outlined" style={{ fontSize: '15px' }}>download</span>
                    Download CV
                  </button>
                </div>

                {/* Reminder status */}
                <div className={`rounded-xl border p-4 ${candidate.reminderOverdue ? 'bg-red-50 border-red-100' : candidate.nextReminderDate ? 'bg-amber-50 border-amber-100' : 'bg-green-50 border-green-100'}`}>
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className={`material-symbols-outlined text-sm ${candidate.reminderOverdue ? 'text-danger' : candidate.nextReminderDate ? 'text-warning' : 'text-success'}`} style={{ fontSize: '16px' }}>
                      {candidate.reminderOverdue ? 'notification_important' : candidate.nextReminderDate ? 'notifications' : 'check_circle'}
                    </span>
                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Reminder</span>
                  </div>
                  <p className="text-xs font-semibold text-slate-700">
                    {candidate.reminderOverdue
                      ? 'Overdue — Follow up immediately'
                      : candidate.nextReminderDate
                      ? `Due ${formatDate(candidate.nextReminderDate)}`
                      : 'No upcoming reminder'}
                  </p>
                </div>
              </div>

              {/* Right column */}
              <div className="col-span-8 space-y-4">
                {/* Pipeline progress */}
                <div className="bg-white rounded-xl border border-slate-200 p-5">
                  <h3 className="text-sm font-semibold text-slate-800 mb-5">Pipeline Progress</h3>
                  <div className="flex items-center">
                    {PIPELINE_STAGES.filter((s) => s !== 'rejected').map((s, i, arr) => {
                      const past    = PIPELINE_STAGES.indexOf(s) < stageIdx && !isRejected
                      const current = s === candidate.stage
                      return (
                        <div key={s} className="flex items-center flex-1">
                          <div className="flex flex-col items-center gap-1.5 flex-1">
                            <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-colors ${current ? 'bg-primary text-white ring-4 ring-primary/20' : past ? 'bg-success text-white' : 'bg-slate-100 text-slate-400'}`}>
                              {past ? '✓' : i + 1}
                            </div>
                            <span className={`text-[10px] font-semibold ${current ? 'text-primary' : past ? 'text-success' : 'text-slate-400'}`}>{STAGE_LABELS[s]}</span>
                          </div>
                          {i < arr.length - 1 && (
                            <div className={`h-0.5 flex-1 mx-1 ${past || current ? 'bg-primary/30' : 'bg-slate-100'}`} />
                          )}
                        </div>
                      )
                    })}
                  </div>
                  {isRejected && (
                    <div className="mt-4 text-center">
                      <span className="text-xs font-semibold bg-red-100 text-red-600 px-3 py-1 rounded-full">Candidate was rejected</span>
                    </div>
                  )}
                </div>

                {/* Details grid */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white rounded-xl border border-slate-200 p-5">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Job Requirements</p>
                    <div className="space-y-2 text-xs">
                      {[
                        { label: 'Japanese Level', value: job?.japaneseLevel },
                        { label: 'English Level',  value: job?.englishLevel },
                        { label: 'Exp Required',   value: `${job?.experienceYears}+ years` },
                        { label: 'Location',       value: job?.location },
                        { label: 'Type',           value: job?.employmentType },
                      ].map(({ label, value }) => (
                        <div key={label} className="flex justify-between">
                          <span className="text-slate-500">{label}</span>
                          <span className="font-semibold text-slate-700">{value ?? '—'}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="bg-white rounded-xl border border-slate-200 p-5">
                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-3">Timeline</p>
                    <div className="space-y-3">
                      {[
                        { label: 'Applied',       date: candidate.appliedDate,       icon: 'send',          color: 'text-slate-400' },
                        { label: 'Last Activity', date: candidate.lastActivityDate,  icon: 'history',       color: 'text-primary' },
                        { label: 'Next Reminder', date: candidate.nextReminderDate, icon: 'notifications',  color: candidate.reminderOverdue ? 'text-danger' : 'text-warning' },
                      ].map(({ label, date, icon, color }) => (
                        <div key={label} className="flex items-center justify-between text-xs">
                          <div className="flex items-center gap-2">
                            <span className={`material-symbols-outlined ${color}`} style={{ fontSize: '14px' }}>{icon}</span>
                            <span className="text-slate-500">{label}</span>
                          </div>
                          <span className="font-medium text-slate-700">{date ? formatDate(date) : '—'}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Skill match */}
                <div className="bg-white rounded-xl border border-slate-200 p-5">
                  <h3 className="text-sm font-semibold text-slate-800 mb-3">Skill Match</h3>
                  <div className="space-y-2">
                    {(job?.requiredSkills ?? []).map((skill) => {
                      const has = candidate.skills.some((s) =>
                        s.toLowerCase().includes(skill.toLowerCase()) || skill.toLowerCase().includes(s.toLowerCase())
                      )
                      return (
                        <div key={skill} className="flex items-center gap-3">
                          <span className={`material-symbols-outlined ${has ? 'text-success' : 'text-slate-200'}`} style={{ fontSize: '15px' }}>
                            {has ? 'check_circle' : 'radio_button_unchecked'}
                          </span>
                          <span className={`text-xs ${has ? 'text-slate-700 font-medium' : 'text-slate-400'}`}>{skill}</span>
                          {has && <span className="ml-auto text-[10px] bg-green-50 text-success px-2 py-0.5 rounded-full font-semibold">Matched</span>}
                        </div>
                      )
                    })}
                  </div>
                </div>

                {/* Background (from CV) */}
                {((candidate.workExperience?.length ?? 0) > 0 ||
                  (candidate.education?.length ?? 0) > 0 ||
                  (candidate.certifications?.length ?? 0) > 0 ||
                  (candidate.languages?.length ?? 0) > 0) && (
                  <div className="bg-white rounded-xl border border-slate-200 p-5 space-y-5">
                    <h3 className="text-sm font-semibold text-slate-800">Background</h3>

                    {(candidate.workExperience?.length ?? 0) > 0 && (
                      <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Work Experience</p>
                        <div className="space-y-3">
                          {candidate.workExperience!.map((exp) => (
                            <div key={exp.id} className="border-l-2 border-slate-100 pl-3">
                              <p className="text-sm font-semibold text-slate-700">{exp.position}{exp.company ? ` · ${exp.company}` : ''}</p>
                              <p className="text-xs text-slate-400">{exp.startDate} – {exp.isCurrent ? 'Present' : exp.endDate}</p>
                              {exp.description && <p className="text-xs text-slate-600 mt-1">{exp.description}</p>}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {(candidate.education?.length ?? 0) > 0 && (
                      <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Education</p>
                        <div className="space-y-2">
                          {candidate.education!.map((edu) => (
                            <div key={edu.id} className="text-xs text-slate-600">
                              <span className="font-semibold text-slate-700">{edu.degree}</span>
                              {edu.major ? `, ${edu.major}` : ''} — {edu.institution} {edu.graduationYear && `(${edu.graduationYear})`}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {(candidate.languages?.length ?? 0) > 0 && (
                      <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Languages</p>
                        <div className="flex flex-wrap gap-1.5">
                          {candidate.languages!.map((l) => (
                            <span key={l.id} className="text-xs bg-slate-50 text-slate-600 font-medium px-2 py-0.5 rounded-full capitalize">{l.language} · {l.level}</span>
                          ))}
                        </div>
                      </div>
                    )}

                    {(candidate.certifications?.length ?? 0) > 0 && (
                      <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Certifications</p>
                        <div className="space-y-1">
                          {candidate.certifications!.map((c) => (
                            <div key={c.id} className="text-xs text-slate-600">
                              <span className="font-semibold text-slate-700">{c.name}</span> — {c.organization} {c.date && `(${c.date})`}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* ── ACTIVITY ── */}
          {tab === 'activity' && (
            <div className="max-w-2xl">
              {relatedLogs.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-20 text-center">
                  <div className="w-12 h-12 rounded-2xl bg-slate-100 flex items-center justify-center mb-3 text-xl">📋</div>
                  <p className="text-sm font-semibold text-slate-500">No activity yet</p>
                  <p className="text-xs text-slate-400 mt-1">Activities for this candidate will appear here</p>
                </div>
              ) : (
                <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                  {relatedLogs.map((log, i) => (
                    <div key={log.id} className={`flex items-start gap-3 px-4 py-3 ${i < relatedLogs.length - 1 ? 'border-b border-slate-50' : ''}`}>
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 bg-blue-50 text-blue-600 text-sm mt-0.5">
                        {log.type === 'Call' ? '📞' : log.type === 'Email' ? '📧' : log.type === 'Meeting' ? '📅' : '💬'}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-xs font-semibold text-slate-700">{log.type}</span>
                          <span className="text-[10px] text-slate-400">{log.date}</span>
                        </div>
                        <p className="text-xs text-slate-600 leading-relaxed">{log.summary}</p>
                        {log.nextAction && (
                          <div className="mt-1.5 flex items-center gap-1 text-[11px] text-primary font-medium">
                            <span className="material-symbols-outlined" style={{ fontSize: '11px' }}>arrow_forward</span>
                            {log.nextAction}
                          </div>
                        )}
                      </div>
                      <span className="text-[10px] text-slate-400 flex-shrink-0">{log.author}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* ── REMINDERS ── */}
          {tab === 'reminders' && (
            <div className="max-w-2xl space-y-3">
              {relatedReminders.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-20 text-center">
                  <div className="w-12 h-12 rounded-2xl bg-slate-100 flex items-center justify-center mb-3 text-xl">🔔</div>
                  <p className="text-sm font-semibold text-slate-500">No reminders for this candidate</p>
                  <button onClick={() => navigate('/reminders')} className="text-xs text-primary hover:underline font-medium mt-2">
                    Go to Reminders →
                  </button>
                </div>
              ) : (
                <>
                  {openReminders.length > 0 && (
                    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                      <div className="px-4 py-2.5 border-b border-slate-50 bg-slate-50">
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Open ({openReminders.length})</span>
                      </div>
                      {openReminders.map((r, i) => {
                        const isOverdue = r.dueDate < TODAY
                        return (
                          <div key={r.id} className={`flex items-start gap-3 px-4 py-3 ${isOverdue ? 'border-l-2 border-l-red-400' : r.dueDate === TODAY ? 'border-l-2 border-l-amber-400' : 'border-l-2 border-l-transparent'} ${i < openReminders.length - 1 ? 'border-b border-slate-50' : ''}`}>
                            <div className={`flex-shrink-0 mt-0.5 w-4 h-4 rounded border-2 border-slate-300`} />
                            <div className="flex-1 min-w-0">
                              <p className="text-xs font-semibold text-slate-800">{r.title}</p>
                              <p className={`text-[11px] font-medium mt-0.5 ${isOverdue ? 'text-red-500' : r.dueDate === TODAY ? 'text-amber-600' : 'text-slate-400'}`}>
                                {formatDate(r.dueDate)} · {daysUntil(r.dueDate)}
                              </p>
                            </div>
                            <span className={`flex-shrink-0 text-[10px] font-bold px-1.5 py-0.5 rounded-full ${r.priority === 'high' ? 'text-red-600 bg-red-50' : r.priority === 'medium' ? 'text-amber-600 bg-amber-50' : 'text-slate-400 bg-slate-100'}`}>
                              {r.priority}
                            </span>
                          </div>
                        )
                      })}
                    </div>
                  )}
                  {doneReminders.length > 0 && (
                    <div className="bg-white rounded-xl border border-slate-200 overflow-hidden opacity-70">
                      <div className="px-4 py-2.5 border-b border-slate-50 bg-slate-50">
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Completed ({doneReminders.length})</span>
                      </div>
                      {doneReminders.map((r, i) => (
                        <div key={r.id} className={`flex items-start gap-3 px-4 py-3 ${i < doneReminders.length - 1 ? 'border-b border-slate-50' : ''}`}>
                          <div className="flex-shrink-0 mt-0.5 w-4 h-4 rounded border-2 border-slate-300 bg-slate-200 flex items-center justify-center">
                            <span className="material-symbols-outlined text-slate-500" style={{ fontSize: '10px' }}>check</span>
                          </div>
                          <p className="text-xs text-slate-400 line-through">{r.title}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
          )}

        </div>
      </div>
    </div>
  )
}
