import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Sidebar from '../../components/Sidebar'
import PageHeader from '../../components/PageHeader'
import StepIndicator from '../../components/cv/StepIndicator'
import { useCVContext } from '../../context/CVContext'
import { cvTemplates } from '../../data/cvMockData'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 pb-1 border-b border-slate-100">{title}</h3>
      {children}
    </div>
  )
}

export default function CVPreviewPage() {
  const navigate = useNavigate()
  const { session, history, resetSession } = useCVContext()

  const latest      = history[0]
  const candidate   = session.parsedData
  const template    = cvTemplates.find((t) => t.id === (session.selectedTemplateId ?? latest?.templateId))
  const name        = session.candidateName  || candidate?.fullName  || latest?.candidateName  || 'Candidate Name'
  const email       = session.candidateEmail || candidate?.email     || latest?.candidateEmail || ''
  const phone       = candidate?.phone       || '+95-9-1234-5678'
  const address     = candidate?.address     || 'Yangon, Myanmar'
  const summary     = candidate?.workExperience?.[0]?.description    || 'Experienced professional with strong technical background.'
  const skills      = candidate?.skills      || ['Java', 'Spring Boot', 'Docker', 'Kubernetes']
  const experiences = candidate?.workExperience ?? []
  const education   = candidate?.education   ?? []
  const languages   = candidate?.languages   ?? []
  const certs       = candidate?.certifications ?? []
  const format      = session.outputFormat   ?? latest?.outputFormat ?? 'pdf'

  const [zoom, setZoom] = useState(100)

  function handleDownload() {
    const lines = [
      `════════════════════════════════════════`,
      `  ${name}`,
      `  ${email} · ${phone}`,
      `  ${address}`,
      `════════════════════════════════════════`,
      '',
      'PROFESSIONAL SUMMARY',
      '─────────────────────────────────────────',
      summary,
      '',
      'SKILLS',
      '─────────────────────────────────────────',
      skills.join(' · '),
      '',
      'WORK EXPERIENCE',
      '─────────────────────────────────────────',
      ...experiences.map((e) => [
        `${e.position} @ ${e.company}`,
        `${e.startDate} – ${e.isCurrent ? 'Present' : e.endDate}`,
        e.description,
        '',
      ].join('\n')),
      '',
      'EDUCATION',
      '─────────────────────────────────────────',
      ...education.map((e) => `${e.degree}, ${e.major} — ${e.institution} (${e.graduationYear})`),
      '',
      'LANGUAGES',
      '─────────────────────────────────────────',
      ...languages.map((l) => `${l.language} (${l.level})`),
      '',
      'CERTIFICATIONS',
      '─────────────────────────────────────────',
      ...certs.map((c) => `${c.name} — ${c.organization} (${c.date})`),
      '',
      `────────────────────────────────────────`,
      `Generated by RecruitSync · Template: ${template?.name ?? 'Standard'}`,
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${name.replace(/ /g, '_')}_CV.${format === 'both' ? 'txt' : format === 'docx' ? 'txt' : 'txt'}`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex h-screen bg-surface overflow-hidden">
      <Sidebar />
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        <PageHeader
          title="CV Preview"
          subtitle="Step 5 of 5 — Review the generated CV before download"
          actions={
            <div className="flex items-center gap-2">
              <button onClick={handleDownload}
                className="flex items-center gap-1.5 bg-success text-white text-sm font-semibold px-4 py-2 rounded-lg hover:opacity-90 transition-opacity">
                <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>download</span>
                Download {format === 'both' ? 'PDF + DOCX' : format.toUpperCase()}
              </button>
              <button onClick={() => { resetSession(); navigate('/cv/upload') }}
                className="text-sm font-medium text-slate-600 bg-white border border-slate-200 px-4 py-2 rounded-lg hover:bg-slate-50 transition-colors">
                Start Over
              </button>
            </div>
          }
        />
        <StepIndicator currentPath="/cv/preview" />

        <div className="flex-1 flex overflow-hidden">
          {/* Left panel — metadata */}
          <div className="w-64 flex-shrink-0 border-r border-slate-200 bg-white overflow-y-auto p-5 space-y-5">
            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Template</p>
              <div className="flex items-center gap-2.5">
                {template && (
                  <div className="w-8 h-8 rounded-lg flex-shrink-0" style={{ backgroundColor: template.thumbnailColor }} />
                )}
                <p className="text-xs font-semibold text-slate-700 leading-snug">{template?.name ?? '—'}</p>
              </div>
            </div>

            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Format</p>
              <span className="text-xs font-mono font-bold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                {format === 'both' ? 'PDF + DOCX' : format.toUpperCase()}
              </span>
            </div>

            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Candidate</p>
              <p className="text-xs font-semibold text-slate-700">{name}</p>
              <p className="text-xs text-slate-400">{email}</p>
            </div>

            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Source Files</p>
              <div className="space-y-1">
                {session.files.map((f) => (
                  <div key={f.id} className="flex items-center gap-1.5">
                    <span className="material-symbols-outlined text-slate-400" style={{ fontSize: '12px' }}>attach_file</span>
                    <span className="text-xs text-slate-500 truncate">{f.name}</span>
                  </div>
                ))}
                {session.files.length === 0 && <p className="text-xs text-slate-300">Demo mode</p>}
              </div>
            </div>

            {/* Zoom */}
            <div>
              <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Zoom</p>
              <div className="flex items-center gap-2">
                <button onClick={() => setZoom((z) => Math.max(50, z - 10))} className="w-6 h-6 flex items-center justify-center rounded border border-slate-200 hover:bg-slate-50 text-slate-500">
                  <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>remove</span>
                </button>
                <span className="text-xs font-mono text-slate-700 w-10 text-center">{zoom}%</span>
                <button onClick={() => setZoom((z) => Math.min(150, z + 10))} className="w-6 h-6 flex items-center justify-center rounded border border-slate-200 hover:bg-slate-50 text-slate-500">
                  <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>add</span>
                </button>
              </div>
            </div>

            <div className="pt-3 border-t border-slate-100 space-y-2">
              <button onClick={() => navigate('/cv/templates')} className="w-full text-xs font-medium text-slate-500 hover:text-slate-700 flex items-center gap-1">
                <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>arrow_back</span>Change Template
              </button>
              <button onClick={() => navigate('/cv')} className="w-full text-xs font-medium text-primary hover:underline flex items-center gap-1">
                <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>home</span>Back to Dashboard
              </button>
            </div>
          </div>

          {/* Right panel — preview */}
          <div className="flex-1 overflow-auto bg-slate-100 p-8 flex justify-center">
            <div
              style={{ transform: `scale(${zoom / 100})`, transformOrigin: 'top center', transition: 'transform 0.15s', width: '680px' }}
              className="bg-white shadow-xl rounded-lg overflow-hidden"
            >
              {/* Header band */}
              {template && (
                <div className="h-2" style={{ backgroundColor: template.thumbnailColor }} />
              )}
              <div className="px-10 py-8">
                {/* Name block */}
                <div className="mb-6 pb-5 border-b-2 border-slate-100">
                  <h1 className="text-2xl font-bold text-slate-900">{name}</h1>
                  <p className="text-sm font-semibold text-slate-500 mt-0.5">{candidate?.currentJobTitle ?? 'Software Engineer'}</p>
                  <div className="flex flex-wrap gap-4 mt-2 text-xs text-slate-500">
                    {email  && <span className="flex items-center gap-1"><span className="material-symbols-outlined" style={{ fontSize: '12px' }}>mail</span>{email}</span>}
                    {phone  && <span className="flex items-center gap-1"><span className="material-symbols-outlined" style={{ fontSize: '12px' }}>phone</span>{phone}</span>}
                    {address && <span className="flex items-center gap-1"><span className="material-symbols-outlined" style={{ fontSize: '12px' }}>location_on</span>{address}</span>}
                  </div>
                </div>

                {summary && (
                  <Section title="Professional Summary">
                    <p className="text-xs text-slate-600 leading-relaxed">{summary}</p>
                  </Section>
                )}

                {skills.length > 0 && (
                  <Section title="Skills">
                    <div className="flex flex-wrap gap-1.5">
                      {skills.map((s) => (
                        <span key={s} className="text-xs bg-slate-100 text-slate-700 px-2 py-0.5 rounded font-medium">{s}</span>
                      ))}
                    </div>
                  </Section>
                )}

                {experiences.length > 0 && (
                  <Section title="Work Experience">
                    <div className="space-y-4">
                      {experiences.map((exp) => (
                        <div key={exp.id}>
                          <div className="flex items-start justify-between">
                            <div>
                              <p className="text-xs font-bold text-slate-800">{exp.position}</p>
                              <p className="text-xs text-slate-500">{exp.company}</p>
                            </div>
                            <p className="text-xs text-slate-400 whitespace-nowrap ml-4">{exp.startDate} – {exp.isCurrent ? 'Present' : exp.endDate}</p>
                          </div>
                          <p className="text-xs text-slate-600 mt-1 leading-relaxed">{exp.description}</p>
                          {exp.technologies && (
                            <div className="flex flex-wrap gap-1 mt-1.5">
                              {exp.technologies.map((t) => (
                                <span key={t} className="text-xs bg-blue-50 text-blue-700 px-1.5 py-0.5 rounded">{t}</span>
                              ))}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </Section>
                )}

                {education.length > 0 && (
                  <Section title="Education">
                    {education.map((edu) => (
                      <div key={edu.id} className="flex items-start justify-between">
                        <div>
                          <p className="text-xs font-bold text-slate-800">{edu.degree}{edu.major ? `, ${edu.major}` : ''}</p>
                          <p className="text-xs text-slate-500">{edu.institution}</p>
                        </div>
                        <p className="text-xs text-slate-400 ml-4">{edu.graduationYear}</p>
                      </div>
                    ))}
                  </Section>
                )}

                {languages.length > 0 && (
                  <Section title="Languages">
                    <div className="flex flex-wrap gap-4">
                      {languages.map((l) => (
                        <div key={l.id} className="text-xs">
                          <span className="font-semibold text-slate-700">{l.language}</span>
                          <span className="text-slate-400 ml-1 capitalize">({l.level})</span>
                        </div>
                      ))}
                    </div>
                  </Section>
                )}

                {certs.length > 0 && (
                  <Section title="Certifications">
                    <div className="space-y-1">
                      {certs.map((c) => (
                        <div key={c.id} className="flex items-start justify-between">
                          <p className="text-xs font-semibold text-slate-700">{c.name}</p>
                          <p className="text-xs text-slate-400 ml-4 whitespace-nowrap">{c.organization} · {c.date}</p>
                        </div>
                      ))}
                    </div>
                  </Section>
                )}

                <div className="mt-8 pt-4 border-t border-slate-100 text-xs text-slate-300 text-center">
                  Generated by RecruitSync · Template: {template?.name ?? 'Standard'} · {new Date().toLocaleDateString('en-GB')}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
